# Header
head_img: http://oav778tsj.bkt.clouddn.com/head_pic.jpg

# Content


index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Writing
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace:
  style: 'github'

# Miscellaneous
google_analytics:
favicon: /favicon.png
theme: happiness
github:
douban:
weibo:
